### ISSUE TITLE
前端访问不到后端,需要启动nginx吗

### ISSUE THREAD

**Issue by allbluefs** [19920625lsg/spring-boot-online-exam#23]

**Comment by 19920625lsg** [comment]
开发模式下vue脚手架有提供[反向代理](https://github.com/19920625lsg/spring-boot-online-exam/blob/master/frontend/exam/vue.config.js#L88),如果需要部署到生产环境地话需要配置下nginx，我倒是也做了demo,见 [nginx.conf](https://github.com/19920625lsg/spring-boot-online-exam/blob/master/doc/deploy/nginx.conf#L23)，root目录改成自己的，把`npm run build`生成的dist目录里的东西拷贝到root路径即可

**Comment by allbluefs** [comment]
> 开发模式下vue脚手架有提供[反向代理](https://github.com/19920625lsg/spring-boot-online-exam/blob/master/frontend/exam/vue.config.js#L88),如果需要部署到生产环境地话需要配置下nginx，我倒是也做了demo,见 [nginx.conf](https://github.com/19920625lsg/spring-boot-online-exam/blob/master/doc/deploy/nginx.conf#L23)，root目录改成自己的，把`npm run build`生成的dist目录里的东西拷贝到root路径即可

弄好了,谢谢你
