### ISSUE TITLE
为什么创建考试可以，新建问题出现'create_time' cannot be null

### ISSUE THREAD

**Issue by Jackwanping** [19920625lsg/spring-boot-online-exam#29]
![image](https://user-images.githubusercontent.com/33993900/80057892-4d616200-855a-11ea-8d46-b6beda3f92d1.png)
create_time 是自动插入的，怎么会空？求翻！

**Comment by 19920625lsg** [comment]
实在抱歉这么久才回复哈~create_time我在数据库层面设置自动生成了，后面迁移数据库不知道怎么漏了，我干脆在代码里直接加上了 https://github.com/19920625lsg/spring-boot-online-exam/commit/ce25b7777164cd4ccacd524dbe9a8e8e795fc401
