### ISSUE TITLE
请问在spring-boot-online-exam/backend/exam/src/main/resources/application.yml中是没有password的选项的，只有后面application-dev和application-prod有而且密码不一样，希望能重新更新一下安装配置教程，新手真的好难看懂，谢谢，辛苦了

### ISSUE THREAD

**Issue by zerolanlan** [19920625lsg/spring-boot-online-exam#47]

**Comment by 19920625lsg** [comment]
这是springboot区分dev和prod环境的方式，application.yml有`profiles.active:dev`就是制定加载application-dev.yml的，这个是springboot基础哦~~建议先系统学一下springboot哈

**Comment by zerolanlan** [comment]
感谢你的解答，谢谢，懂了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "19920625lsg/spring-boot-online-exam"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 上午9:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [19920625lsg/spring-boot-online-exam] 请问在spring-boot-online-exam/backend/exam/src/main/resources/application.yml中是没有password的选项的，只有后面application-dev和application-prod有而且密码不一样，希望能重新更新一下安装配置教程，新手真的好难看懂，谢谢，辛苦了 (#47)





 
这是springboot区分dev和prod环境的方式，application.yml有profiles.active:dev就是制定加载application-dev.yml的，这个是springboot基础哦~~建议先系统学一下springboot哈
