### ISSUE TITLE
为什么会在Service里面用Mapper?

### ISSUE THREAD

**Issue by ranter123** [19920625lsg/spring-boot-online-exam#5]
![image](https://user-images.githubusercontent.com/28686768/54866482-337daa80-4daf-11e9-88ba-f88e96fa66cc.png)
不能改分层隔离吗？这段代码也属于错误的吧（直接使用interface对象类）。

**Comment by FunctionD** [comment]
...不在service里调mapper在哪调？
...@Autowird是用来干嘛的？
