### ISSUE TITLE
我把服务都起来了，然后能防问admin-service的登录页，可是登录后又跳转到登录页呢？

### ISSUE THREAD

**Issue by wi6146149** [19920625lsg/spring-boot-online-exam#7]
我使用注册功能，发现是可以注册信息到数据库，说明数据库连接正常。我去看登录页表单的action，它是向login这个提交的，可是我没有找到这个login的控制器，想问问是怎么情况呢？

**Comment by fangtenglong** [comment]
> 我使用注册功能，发现是可以注册信息到数据库，说明数据库连接正常。我去看登录页表单的action，它是向login这个提交的，可是我没有找到这个login的控制器，想问问是怎么情况呢？

能教一下如何把这个项目跑起来吗

**Comment by jingjing666666** [comment]
用的SpringSecurity，然后用userDetailService校验的
